"""tao toan bo bang theo muc 8.2 cua plan

Revision ID: 4f6a7f86f019
Revises: 
Create Date: 2026-08-30 01:33:20.204418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6a7f86f019'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_session_id'), 'audit_log', ['session_id'], unique=False)
    op.create_table('field_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_history_session_id'), 'field_history', ['session_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_session_id', sa.Uuid(), nullable=True),
    sa.Column('staff_name', sa.String(length=200), nullable=False),
    sa.Column('procedure_code', sa.String(length=100), nullable=True),
    sa.Column('catalog_version', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('citizen_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('citizen_ref', sa.String(length=64), nullable=True),
    sa.Column('dossier_code', sa.String(length=100), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    # duration_ms KHÔNG tạo ở đây — cột tính toán (GENERATED ALWAYS AS ... STORED)
    # được thêm ở migration kế tiếp (xem revision "them cot tinh toan duration_ms").
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('CREATED', 'LISTENING', 'PROCEDURE_SELECTED', 'EXTRACTING', 'SUGGESTED', 'AI_UNAVAILABLE', 'REVIEWING', 'FIELDS_CONFIRMED', 'READBACK', 'CITIZEN_CONFIRMED', 'COMPLETED', 'CANCELLED')", name='chk_state'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_parent_session_id'), 'sessions', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_sessions_procedure_code'), 'sessions', ['procedure_code'], unique=False)
    op.create_index(op.f('ix_sessions_state'), 'sessions', ['state'], unique=False)
    op.create_table('citizen_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('readback_round', sa.Integer(), nullable=False),
    sa.Column('readback_text', sa.Text(), nullable=False),
    sa.Column('readback_method', sa.String(length=20), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_confirmations_session_id'), 'citizen_confirmations', ['session_id'], unique=False)
    op.create_table('field_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('suggested_by', sa.String(length=30), nullable=True),
    sa.Column('ai_confidence', sa.String(length=10), nullable=True),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('confirmed_value', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_edited', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'field_name', name='uq_field_state_session_field')
    )
    op.create_index(op.f('ix_field_states_session_id'), 'field_states', ['session_id'], unique=False)
    op.create_table('voice_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('edited_transcript', sa.Text(), nullable=True),
    sa.Column('flagged_by_staff', sa.Boolean(), nullable=False),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stt_provider', sa.String(length=50), nullable=True),
    sa.Column('stt_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_number', name='uq_turn_session_number')
    )
    op.create_index(op.f('ix_voice_turns_session_id'), 'voice_turns', ['session_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('voice_turn_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_redacted', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_turn_id'], ['voice_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_session_id'), 'extractions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extractions_session_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_voice_turns_session_id'), table_name='voice_turns')
    op.drop_table('voice_turns')
    op.drop_index(op.f('ix_field_states_session_id'), table_name='field_states')
    op.drop_table('field_states')
    op.drop_index(op.f('ix_citizen_confirmations_session_id'), table_name='citizen_confirmations')
    op.drop_table('citizen_confirmations')
    op.drop_index(op.f('ix_sessions_state'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_procedure_code'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_parent_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_field_history_session_id'), table_name='field_history')
    op.drop_table('field_history')
    op.drop_index(op.f('ix_audit_log_session_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
