PRIORITY_KEYWORDS = [
    "Đăng ký khai sinh",
    "Đăng ký khai sinh có yếu tố nước ngoài",
    "Đăng ký lại khai sinh",
    "Đăng ký khai tử",
    "Đăng ký khai tử có yếu tố nước ngoài",
    "Đăng ký lại khai tử",
    "Đăng ký kết hôn",
    "Đăng ký kết hôn có yếu tố nước ngoài",
    "Ghi vào sổ hộ tịch việc kết hôn",
    "Đăng ký lại kết hôn",
    "Ly hôn",
    "Đăng ký nhận cha mẹ con",
    "Đăng ký giám hộ",
    "Cải chính hộ tịch",
    "Thay đổi hộ tịch",
    "Xác định lại dân tộc",
    "Bổ sung hộ tịch",
    "Trích lục hộ tịch",
    "Bản sao trích lục hộ tịch",
    "Đăng ký nuôi con nuôi",
    "Đăng ký thường trú",
    "Đăng ký tạm trú",
    "Khai báo tạm vắng",
    "Tách hộ",
    "Xác nhận thông tin về cư trú",
    "Thẻ căn cước công dân",
    "Cấp đổi thẻ căn cước công dân",
    "Cấp lại thẻ căn cước công dân",
    "Hộ kinh doanh",
    "Đăng ký hộ kinh doanh",
    "Thay đổi nội dung đăng ký hộ kinh doanh",
    "Tạm ngừng hộ kinh doanh",
    "Chấm dứt hoạt động hộ kinh doanh",
    "Doanh nghiệp tư nhân",
    "Công ty trách nhiệm hữu hạn",
    "Công ty cổ phần",
    "Giải thể doanh nghiệp",
    "Đăng ký thuế",
    "Mã số thuế cá nhân",
    "Quyết toán thuế thu nhập cá nhân",
    "Giấy phép lái xe",
    "Cấp đổi giấy phép lái xe",
    "Cấp lại giấy phép lái xe",
    "Sát hạch lái xe",
    "Đăng ký xe",
    "Sang tên xe",
    "Đăng kiểm xe",
    "Bảo hiểm xe cơ giới",
    "Sổ bảo hiểm xã hội",
    "Cấp lại sổ bảo hiểm xã hội",
    "Chế độ ốm đau",
    "Chế độ thai sản",
    "Bảo hiểm thất nghiệp",
    "Hưởng bảo hiểm xã hội một lần",
    "Chế độ hưu trí",
    "Thẻ bảo hiểm y tế",
    "Cấp lại thẻ bảo hiểm y tế",
    "Đổi thẻ bảo hiểm y tế",
    "Khám chữa bệnh bảo hiểm y tế",
    "Giấy chứng nhận nghỉ việc hưởng bảo hiểm xã hội",
    "Giám định y khoa",
    "Khám sức khỏe",
    "Giấy chứng nhận sức khỏe",
    "Hộ chiếu phổ thông",
    "Cấp hộ chiếu phổ thông",
    "Gia hạn hộ chiếu",
    "Thị thực",
    "Cấp thị thực Việt Nam",
    "Gia hạn tạm trú cho người nước ngoài",
    "Thẻ tạm trú cho người nước ngoài",
    "Giấy phép lao động cho người nước ngoài",
    "Xác nhận không thuộc diện cấp giấy phép lao động",
    "Lữ hành quốc tế",
    "Kinh doanh dịch vụ lữ hành",
    "Cấp thẻ hướng dẫn viên du lịch",
    "Xếp hạng cơ sở lưu trú du lịch",
    "Giấy xác nhận tình trạng hôn nhân",
    "Giấy xác nhận độc thân",
    "Phiếu lý lịch tư pháp",
    "Phiếu lý lịch tư pháp số 1",
    "Phiếu lý lịch tư pháp số 2",
    "Công chứng hợp đồng",
    "Chứng thực bản sao từ bản chính",
    "Chứng thực chữ ký",
    "Chứng thực hợp đồng giao dịch",
    "Giấy chứng nhận quyền sử dụng đất",
    "Cấp đổi giấy chứng nhận quyền sử dụng đất",
    "Đăng ký biến động đất đai",
    "Chuyển mục đích sử dụng đất",
    "Tách thửa đất",
    "Hợp thửa đất",
    "Giấy phép xây dựng",
    "Giấy phép xây dựng nhà ở riêng lẻ",
    "Đăng ký khai sinh kết hợp nhận cha mẹ con",
    "Trợ cấp xã hội",
    "Hộ nghèo",
    "Hộ cận nghèo",
    "Bảo trợ xã hội",
    "Người khuyết tật",
    "Học nghề",
    "Miễn giảm học phí",
    "Văn bằng chứng chỉ",
    "An toàn thực phẩm",
    "Trẻ em có hoàn cảnh đặc biệt",
]
