KEYWORDS = [
    "Đăng ký khai sinh",
    "Đăng ký khai tử",
    "Đăng ký kết hôn",
    "Ghi vào sổ hộ tịch",
    "Đăng ký nhận cha mẹ con",
    "Đăng ký giám hộ",
    "Cải chính hộ tịch",
    "Xác định lại dân tộc",
    "Bổ sung hộ tịch",
    "Trích lục hộ tịch",
    "Đăng ký nuôi con nuôi",
    "Đăng ký thường trú",
    "Đăng ký tạm trú",
    "Khai báo tạm vắng",
    "Tách hộ",
    "Thông tin về cư trú",
    "Thẻ căn cước",
    "Giấy chứng nhận căn cước",
    "Hộ kinh doanh",
    "Doanh nghiệp tư nhân",
    "Công ty trách nhiệm hữu hạn",
    "Công ty cổ phần",
    "Giải thể doanh nghiệp",
    "Đăng ký thuế",
    "Mã số thuế",
    "Quyết toán thuế thu nhập cá nhân",
    "Đăng ký đầu tư",
    "Giấy phép lao động",
    "Giấy chứng nhận quyền sử dụng đất",
    "Biến động đất đai",
    "Chuyển mục đích sử dụng đất",
    "Tách thửa đất",
    "Hợp thửa đất",
    "Giấy phép xây dựng",
    "Thế chấp quyền sử dụng đất",
    "Phiếu lý lịch tư pháp",
    "Giấy xác nhận tình trạng hôn nhân",
    "Bản sao giấy khai sinh",
    "Bản sao giấy chứng tử",
    "Hộ chiếu phổ thông",
    "Thị thực",
    "Tạm trú cho người nước ngoài",
    "Giấy phép lái xe",
    "Đăng ký xe",
    "Sang tên xe",
    "Đăng kiểm xe",
    "Bảo hiểm xe",
    "Giấy xác nhận độc thân",
    "Hợp đồng lao động",
    "Nội quy lao động",
    "Sổ bảo hiểm xã hội",
    "Chế độ ốm đau",
    "Chế độ thai sản",
    "Bảo hiểm thất nghiệp",
    "Thẻ bảo hiểm y tế",
    "Khám chữa bệnh ban đầu",
    "Học nghề",
    "Miễn giảm học phí",
    "Văn bằng chứng chỉ",
    "Công chứng hợp đồng",
    "Chứng thực bản sao",
    "Chứng thực chữ ký",
    "Chứng thực hợp đồng",
    "Trẻ bị bỏ rơi",
    "Chứng minh nhân dân",
    "Kinh doanh vận tải",
    "Phù hiệu xe",
    "An toàn thực phẩm",
    "Công bố hợp quy",
    "Tiêu chuẩn chất lượng sản phẩm",
    "Đăng ký nhãn hiệu",
    "Bản quyền tác giả",
    "Đăng ký sáng chế",
    "Mã số mã vạch",
    "Giấy phép quảng cáo",
    "Giấy phép hoạt động in",
    "Hoạt động tôn giáo",
    "Hội và tổ chức phi chính phủ",
    "Giấy phép xây dựng nhà ở",
    "Quyền sở hữu nhà ở",
    "Giám sát việc giám hộ",
    "Xác nhận nơi cư trú",
    "Giấy thông hành",
    "Giấy phép xuất cảnh",
    "Lý lịch tư pháp không có tiền án",
    "Thay đổi họ tên",
    "Xác định lại giới tính",
]
